export const ministries = [
  {
    slug: "spiritual-service",
    name: "Spiritual Service Ministry",
    description: "Dedicated to nurturing the spiritual growth of our congregation through worship and devotion.",
    leader: "Pastor Tadesse Bekele",
    meetingTime: "Sunday 2:00 PM",
    purpose: "To deepen the spiritual lives of believers through structured worship services, prayer meetings, and spiritual mentorship programs.",
    schedule: "Every Sunday at 2:00 PM before the main service",
    whoCanJoin: "All church members who desire to serve in the spiritual growth of the congregation.",
    icon: "Heart",
  },
  {
    slug: "teaching-seminar",
    name: "Teaching and Seminar Ministry",
    description: "Providing biblical education and in-depth theological training for all age groups.",
    leader: "Dr. Mekonnen Girma",
    meetingTime: "Saturday 4:00 PM",
    purpose: "To equip believers with sound biblical knowledge through seminars, workshops, and systematic Bible study programs.",
    schedule: "Every Saturday at 4:00 PM",
    whoCanJoin: "Open to all church members and visitors who seek to grow in biblical understanding.",
    icon: "BookOpen",
  },
  {
    slug: "womens-ministry",
    name: "Women's Ministry",
    description: "Empowering women through fellowship, prayer, and community outreach.",
    leader: "Sister Almaz Tesfaye",
    meetingTime: "Saturday 2:00 PM",
    purpose: "To build a strong community of women who support each other in faith, family, and service.",
    schedule: "Every Saturday at 2:00 PM",
    whoCanJoin: "All women of the church and community are welcome.",
    icon: "Users",
  },
  {
    slug: "youth-ministry",
    name: "Youth Ministry",
    description: "Engaging young people in faith, leadership, and community service.",
    leader: "Brother Daniel Abebe",
    meetingTime: "Friday 5:00 PM",
    purpose: "To disciple young people and equip them for leadership through Bible study, fellowship, and outreach activities.",
    schedule: "Every Friday at 5:00 PM",
    whoCanJoin: "Youth aged 15-30 are welcome to join.",
    icon: "Zap",
  },
  {
    slug: "children-ministry",
    name: "Children Ministry",
    description: "Teaching children the love of God through age-appropriate lessons and activities.",
    leader: "Sister Hanna Worku",
    meetingTime: "Sunday 3:00 PM",
    purpose: "To lay a strong spiritual foundation in children through creative teaching, songs, and interactive Bible stories.",
    schedule: "Every Sunday during the main service at 3:00 PM",
    whoCanJoin: "Children aged 3-14 and volunteers who love working with kids.",
    icon: "Baby",
  },
  {
    slug: "mission-ministry",
    name: "Mission Ministry",
    description: "Spreading the Gospel to unreached communities through outreach programs.",
    leader: "Elder Yohannes Hailu",
    meetingTime: "1st Saturday of each month",
    purpose: "To fulfill the Great Commission by supporting missionaries and organizing outreach campaigns.",
    schedule: "Monthly planning meeting on the 1st Saturday",
    whoCanJoin: "Anyone with a heart for evangelism and mission work.",
    icon: "Globe",
  },
  {
    slug: "marriage-family",
    name: "Marriage and Family Ministry",
    description: "Strengthening families through biblical counseling and fellowship events.",
    leader: "Pastor Kebede & Sister Tigist",
    meetingTime: "2nd Sunday of each month",
    purpose: "To build strong, Christ-centered marriages and families through counseling, workshops, and couples' retreats.",
    schedule: "2nd Sunday of each month after service",
    whoCanJoin: "Married couples, engaged couples, and families.",
    icon: "HeartHandshake",
  },
  {
    slug: "prayer-groups",
    name: "Prayer Groups",
    description: "Intercessory prayer for the church, nation, and world.",
    leader: "Deacon Samuel Desta",
    meetingTime: "Wednesday 6:30 PM",
    purpose: "To stand in the gap through intercessory prayer, seeking God's guidance and protection for the church and community.",
    schedule: "Every Wednesday at 6:30 PM",
    whoCanJoin: "All believers who are passionate about prayer.",
    icon: "HandMetal",
  },
  {
    slug: "administration",
    name: "Administration Ministry",
    description: "Ensuring the smooth operation and governance of church activities.",
    leader: "Brother Fikru Assefa",
    meetingTime: "Monday 6:00 PM",
    purpose: "To manage church operations, finances, and logistics with excellence and accountability.",
    schedule: "Every Monday at 6:00 PM",
    whoCanJoin: "Members with skills in administration, finance, or organizational management.",
    icon: "ClipboardList",
  },
  {
    slug: "deacons",
    name: "Deacons",
    description: "Serving the church through practical ministry and community care.",
    leader: "Head Deacon Bereket Tsegaye",
    meetingTime: "1st Wednesday of each month",
    purpose: "To serve the practical needs of the congregation and ensure the welfare of church members.",
    schedule: "1st Wednesday of each month at 6:00 PM",
    whoCanJoin: "Nominated and elected members who meet the biblical qualifications.",
    icon: "Shield",
  },
  {
    slug: "charity-ministry",
    name: "Charity Ministry",
    description: "Reaching out to the less fortunate with love, resources, and support.",
    leader: "Sister Meseret Alem",
    meetingTime: "3rd Saturday of each month",
    purpose: "To demonstrate Christ's love by providing for the physical and material needs of the vulnerable in our community.",
    schedule: "3rd Saturday of each month",
    whoCanJoin: "All members who want to serve the community through charitable work.",
    icon: "Gift",
  },
  {
    slug: "stage-worship",
    name: "Stage and Worship Ministry",
    description: "Leading the congregation in worship through music and creative arts.",
    leader: "Brother Dawit Mengistu",
    meetingTime: "Saturday 3:00 PM (Rehearsal)",
    purpose: "To create an atmosphere of worship that glorifies God and draws people into His presence.",
    schedule: "Rehearsal every Saturday at 3:00 PM, service every Sunday",
    whoCanJoin: "Musicians, singers, sound technicians, and anyone gifted in the arts.",
    icon: "Music",
  },
  {
    slug: "neftalem-choir",
    name: "Neftalem Choir",
    description: "Praising God through choral music and hymns in our rich Ethiopian tradition.",
    leader: "Choir Director Ephrem Tadesse",
    meetingTime: "Thursday 6:00 PM (Rehearsal)",
    purpose: "To glorify God through beautiful choral arrangements that reflect our Ethiopian heritage and Christian faith.",
    schedule: "Rehearsal every Thursday at 6:00 PM",
    whoCanJoin: "Anyone who loves to sing and can commit to regular rehearsals.",
    icon: "Mic",
  },
  {
    slug: "monthly-workers-aid",
    name: "Monthly Workers Aid",
    description: "Supporting church workers and volunteers through coordinated assistance programs.",
    leader: "Brother Getachew Teferi",
    meetingTime: "Last Friday of each month",
    purpose: "To provide material and financial support to those who serve tirelessly in church ministry.",
    schedule: "Last Friday of each month at 5:00 PM",
    whoCanJoin: "All contributing church members.",
    icon: "Wallet",
  },
];

export const events = [
  {
    slug: "easter-celebration-2026",
    title: "Easter Celebration Service",
    description: "Join us for a special Easter celebration service with worship, communion, and a message of hope. This is a wonderful time to invite friends and family to experience the joy of the resurrection.",
    date: "2026-04-05",
    time: "9:00 AM - 12:00 PM",
    location: "Main Sanctuary",
    category: "Church",
  },
  {
    slug: "youth-retreat-2026",
    title: "Annual Youth Retreat",
    description: "A weekend retreat for young people to grow in faith, build friendships, and discover their purpose. Activities include worship, workshops, team-building, and outdoor activities.",
    date: "2026-03-20",
    time: "Friday 4:00 PM - Sunday 2:00 PM",
    location: "Debre Zeit Conference Center",
    category: "Youth",
  },
  {
    slug: "womens-conference-2026",
    title: "Women's Annual Conference",
    description: "A powerful gathering of women from across the region for a day of empowerment, worship, and sisterhood. Guest speakers will share on faith, family, and purpose.",
    date: "2026-04-18",
    time: "9:00 AM - 5:00 PM",
    location: "Church Fellowship Hall",
    category: "Church",
  },
  {
    slug: "community-outreach-march",
    title: "Community Outreach Day",
    description: "Serving our neighborhood with food distribution, clothing donations, and free health screenings. Let's be the hands and feet of Christ in our community.",
    date: "2026-03-15",
    time: "8:00 AM - 2:00 PM",
    location: "Church Grounds",
    category: "Events",
  },
  {
    slug: "prayer-night-march",
    title: "All-Night Prayer Service",
    description: "A night dedicated to seeking God's face through worship, intercession, and the Word. Come expecting to encounter God in a powerful way.",
    date: "2026-03-28",
    time: "9:00 PM - 5:00 AM",
    location: "Main Sanctuary",
    category: "Prayer",
  },
  {
    slug: "childrens-bible-camp",
    title: "Children's Bible Camp",
    description: "A fun and educational week-long camp where children learn Bible stories, sing worship songs, do crafts, and make lasting friendships.",
    date: "2026-06-15",
    time: "9:00 AM - 3:00 PM (Mon-Fri)",
    location: "Children's Ministry Hall",
    category: "Children",
  },
];

export const sermons = [
  {
    slug: "the-power-of-prayer",
    title: "The Power of Prayer",
    speaker: "Pastor Tadesse Bekele",
    date: "2026-02-08",
    series: "Walking with God",
    scripture: "Philippians 4:6-7",
    description: "Discover how prayer transforms our lives and connects us to the heart of God. Learn practical steps to deepen your prayer life and experience breakthrough.",
    videoUrl: "",
  },
  {
    slug: "faith-in-action",
    title: "Faith in Action",
    speaker: "Dr. Mekonnen Girma",
    date: "2026-02-01",
    series: "Walking with God",
    scripture: "James 2:14-26",
    description: "Faith without works is dead. This message explores what it means to live out our faith daily in practical, impactful ways.",
    videoUrl: "",
  },
  {
    slug: "the-good-shepherd",
    title: "The Good Shepherd",
    speaker: "Pastor Tadesse Bekele",
    date: "2026-01-25",
    series: "Knowing Jesus",
    scripture: "John 10:1-18",
    description: "Jesus calls Himself the Good Shepherd who lays down His life for the sheep. Discover the depth of His love and care for you.",
    videoUrl: "",
  },
  {
    slug: "strength-in-weakness",
    title: "Strength in Weakness",
    speaker: "Elder Yohannes Hailu",
    date: "2026-01-18",
    series: "Grace Sufficient",
    scripture: "2 Corinthians 12:9-10",
    description: "God's power is made perfect in weakness. Learn how to find strength and hope even in your most challenging moments.",
    videoUrl: "",
  },
  {
    slug: "unity-in-the-body",
    title: "Unity in the Body of Christ",
    speaker: "Dr. Mekonnen Girma",
    date: "2026-01-11",
    series: "The Church",
    scripture: "Ephesians 4:1-6",
    description: "We are one body with many members. This sermon calls us to pursue unity, love, and cooperation as the family of God.",
    videoUrl: "",
  },
  {
    slug: "the-great-commission",
    title: "The Great Commission",
    speaker: "Pastor Tadesse Bekele",
    date: "2026-01-04",
    series: "Mission Minded",
    scripture: "Matthew 28:18-20",
    description: "Jesus' final command to His disciples was to go and make disciples of all nations. How are we responding to this call today?",
    videoUrl: "",
  },
];

export const announcements = [
  {
    slug: "new-service-times",
    title: "Updated Service Times for 2026",
    date: "2026-02-10",
    category: "Church",
    content: "We are excited to announce our updated service schedule for 2026. Sunday services will now begin at 3:00 PM, with midweek prayer remaining on Wednesday at 6:30 PM. The Teaching and Seminar sessions continue every Saturday at 4:00 PM. Please mark your calendars and join us as we grow together in faith.",
  },
  {
    slug: "youth-retreat-registration",
    title: "Youth Retreat Registration Now Open",
    date: "2026-02-08",
    category: "Youth",
    content: "Registration for the Annual Youth Retreat is now open! The retreat will be held March 20-22 at the Debre Zeit Conference Center. This is an incredible opportunity for young people to grow in their faith and build lasting friendships. Registration forms are available at the church office and online.",
  },
  {
    slug: "prayer-week-announcement",
    title: "Week of Prayer and Fasting",
    date: "2026-02-05",
    category: "Prayer",
    content: "Join us for a special week of prayer and fasting from March 1-7. We will gather each evening at 6:30 PM for corporate prayer. Let us seek God together for revival, healing, and direction. Prayer guides will be distributed at the church entrance.",
  },
  {
    slug: "childrens-program-update",
    title: "New Children's Sunday Program",
    date: "2026-02-01",
    category: "Children",
    content: "Our Children's Ministry is launching an exciting new Sunday program! Starting March 1st, children aged 3-14 will enjoy age-appropriate Bible lessons, worship songs, crafts, and games. Volunteers are needed - please speak with Sister Hanna if you'd like to serve.",
  },
  {
    slug: "easter-preparation",
    title: "Easter Preparation Committee Meeting",
    date: "2026-01-28",
    category: "Events",
    content: "All members of the Easter preparation committee are invited to a planning meeting on February 15th at 2:00 PM in the fellowship hall. We will discuss decorations, special music, outreach plans, and logistics for our Easter celebration service on April 5th.",
  },
];

export const leadership = [
  { name: "Pastor Tadesse Bekele", role: "Senior Pastor", bio: "Serving the church for over 15 years with a passion for preaching and discipleship." },
  { name: "Dr. Mekonnen Girma", role: "Associate Pastor & Teacher", bio: "A theologian and educator dedicated to equipping believers with sound doctrine." },
  { name: "Elder Yohannes Hailu", role: "Elder & Missions Leader", bio: "Leading our missions efforts and overseeing church governance for 10 years." },
  { name: "Deacon Samuel Desta", role: "Head of Prayer Ministry", bio: "A man of prayer who leads our intercessory prayer gatherings with devotion." },
  { name: "Sister Almaz Tesfaye", role: "Women's Ministry Leader", bio: "Empowering women through faith, fellowship, and community outreach." },
  { name: "Brother Daniel Abebe", role: "Youth Ministry Leader", bio: "Passionate about discipling the next generation and mentoring young leaders." },
];

export const testimonies = [
  { name: "Selam K.", quote: "This church changed my life. I found a family here that loved me through my darkest times and helped me discover God's purpose for my life." },
  { name: "Abebe T.", quote: "The teaching ministry helped me understand the Bible in a way I never had before. I am growing daily in my walk with Christ." },
  { name: "Meron G.", quote: "My children love the Sunday school program. They come home singing worship songs and telling me Bible stories. I am so grateful!" },
  { name: "Dawit M.", quote: "Through the prayer groups, I experienced healing in my body and restoration in my marriage. God is truly at work in this church." },
  { name: "Tigist A.", quote: "The women's ministry gave me the courage to share my testimony and serve others. I have found purpose and joy in community." },
];
